# Download makefile system here https://github.com/sudar/Arduino-Makefile

#BOARD_TAG    = pro
ARDUINO_LIBS = EEPROM SPI SoftwareSerial

#MONITOR_PORT = /dev/tty.usbxxx
ARCHITECTURE  = avr
BOARD_SUB     = atmega328p

include ../../../Arduino-Makefile/Arduino.mk
